### PR TITLE
Port to Arm platform with neon SIMD support

### PR DESCRIPTION
**Pull request by yuygfgg**

### CODE REVIEW

**Comment by msg7086** [comment]
After this change, do all Windows builds still work? Do they still compile to the same binary?

**Comment by yuygfgg** [comment]
> After this change, do all Windows builds still work? Do they still compile to the same binary?

I'm not sure about windows because I don't have a x86 windows to test on. However, all changes are made only for arm platform and windows part remained unchanged.

**Comment by msg7086** [comment]
Looks like it failed with gcc on Windows, can you please check?

```
-- Build files have been written to: U:/C/enc-dualsynth/neo-f3kdb/build/gcc-x64
[ 10%] Building CXX object CMakeFiles/neo-f3kdb.dir/main.cpp.obj
[ 20%] Building RC object CMakeFiles/neo-f3kdb.dir/src/version.rc.obj
[ 30%] Building CXX object CMakeFiles/neo-f3kdb.dir/src/core.cpp.obj
[ 40%] Building CXX object CMakeFiles/neo-f3kdb.dir/src/cpuid.cpp.obj
U:/C/enc-dualsynth/neo-f3kdb/src/cpuid.cpp:44:19: warning: extra tokens at end of #ifdef directive
   44 | #ifdef __x86_64__ || defined(__i386__)
      |                   ^~
[ 50%] Building CXX object CMakeFiles/neo-f3kdb.dir/src/flash3kyuu_deband_impl_c.cpp.obj
[ 60%] Building CXX object CMakeFiles/neo-f3kdb.dir/src/flash3kyuu_deband_impl_sse4.cpp.obj
In file included from U:/C/enc-dualsynth/neo-f3kdb/src/flash3kyuu_deband_impl_sse4.cpp:2:
D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/13.2.0/include/smmintrin.h: In function 'void process_plane_info_block(pixel_dither_info*&, const unsigned char*, const __m128i&, const __m128i&, const __m128i&, const __m128i&, const __m128i&, char*&) [with int sample_mode = 1; int ref_part_index = 0]':
D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/13.2.0/include/smmintrin.h:326:1: error: inlining failed in call to 'always_inline' '__m128i _mm_mullo_epi32(__m128i, __m128i)': target specific option mismatch
  326 | _mm_mullo_epi32 (__m128i __X, __m128i __Y)
      | ^~~~~~~~~~~~~~~
In file included from U:/C/enc-dualsynth/neo-f3kdb/src/flash3kyuu_deband_impl_sse4.cpp:6:
U:/C/enc-dualsynth/neo-f3kdb/src/flash3kyuu_deband_sse_base.h:67:38: note: called from here
   67 |         ref_offset1 = _mm_mullo_epi32(src_pitch_vector, temp_ref1); // packed DWORD multiplication
      |                       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/13.2.0/include/smmintrin.h:326:1: error: inlining failed in call to 'always_inline' '__m128i _mm_mullo_epi32(__m128i, __m128i)': target specific option mismatch
  326 | _mm_mullo_epi32 (__m128i __X, __m128i __Y)
      | ^~~~~~~~~~~~~~~
U:/C/enc-dualsynth/neo-f3kdb/src/flash3kyuu_deband_sse_base.h:67:38: note: called from here
   67 |         ref_offset1 = _mm_mullo_epi32(src_pitch_vector, temp_ref1); // packed DWORD multiplication
      |                       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/neo-f3kdb.dir/build.make:137: CMakeFiles/neo-f3kdb.dir/src/flash3kyuu_deband_impl_sse4.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/neo-f3kdb.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by msg7086** [comment]
I noticed that you used both `__i386` and `__i386__`, can you please double check the macros you used?

Also please remove `version.hpp` and `version.rc` in the PR.

**Comment by yuygfgg** [comment]
> I noticed that you used both `__i386` and `__i386__`, can you please double check the macros you used?
> 
> Also please remove `version.hpp` and `version.rc` in the PR.

1. ```__i386``` and``` __i386__``` are exactly the same marco as far as I can tell.
2. removed
3. For the compiling failure, what platform are you currently on? An old CPU without sse4.1 support? I think ```_mm_mullo_epi32``` is a SSE4.1 function and -msse4.1 should have been set by cmake on x86.

I did some cross compile with musl-cross but failed on ```error: 'task' was not declared in this scope; did you mean 'tbb::detail::d1::task```

**Comment by yuygfgg** [comment]
> I noticed that you used both `__i386` and `__i386__`, can you please double check the macros you used?
> 
> Also please remove `version.hpp` and `version.rc` in the PR.

1. ```__i386``` and``` __i386__``` are exactly the same marco as far as I can tell.
2. removed
3. For the compiling failure, what platform are you currently on? An old CPU without sse4.1 support? I think ```_mm_mullo_epi32``` is a SSE4.1 function and -msse4.1 should have been set by cmake on x86.

I did some crosscompile but failed on ```error: 'task' was not declared in this scope; did you mean 'tbb::detail::d1::task```

**Comment by msg7086** [comment]
Looks like you removed the following 2 lines and that caused the problem.
```
file(GLOB SSE41_CODE_IMPL "src/*sse4.cpp")
set_source_files_properties(${SSE41_CODE_IMPL} PROPERTIES COMPILE_FLAGS "-msse4.1")
```

**Comment by yuygfgg** [comment]
Could you please try the patched one again? I also enabled compiler optimization, which surprisingly brought me over 10 times performance.

```
sse2neon+O0 40fps
Ofast 450fps
Ofast+sse2neon 580fps
```

**Pull request merged**
